debug : false
spring:
  web:
    resources:
      static-locations: ["/META-INF/resources/","classpath:/resources/","classpath:/static/","classpath:/public/","classpath:/webapp/","classpath:/templates/"]
# ?????????????????????????????????????????????
  mvc:
    static-path-pattern: "/res/**"
#    ?????????